#!/usr/bin/env bash
set -e

ENV_FILE=".env"

if [ -f "$ENV_FILE" ]; then
  echo "⚠️  $ENV_FILE already exists. Delete it first if you want to start over."
  exit 1
fi

echo ""
echo "DaPlanStan Setup"
echo "================"
echo "This script generates your .env file. You will need accounts for:"
echo "  - Google Cloud (OAuth login)"
echo "  - Anthropic (AI email parsing)"
echo "  - Pexels (trip cover photos)"
echo "  - Postmark (outbound email + optional inbound forwarding)"
echo ""

# ── Prompts ──────────────────────────────────────────────────────────────────

prompt() {
  local label="$1" var_name="$2" default="$3"
  if [ -n "$default" ]; then
    read -rp "  $label [$default]: " value
    echo "${value:-$default}"
  else
    local value=""
    while [ -z "$value" ]; do
      read -rp "  $label: " value
    done
    echo "$value"
  fi
}

echo "── Google OAuth ──────────────────────────────────────────────────────────"
echo "  Create credentials at https://console.cloud.google.com/apis/credentials"
echo "  Authorised redirect URI: http://localhost:3000/auth/google_oauth2/callback"
echo ""
GOOGLE_CLIENT_ID=$(prompt "Google Client ID" GOOGLE_CLIENT_ID)
GOOGLE_CLIENT_SECRET=$(prompt "Google Client Secret" GOOGLE_CLIENT_SECRET)

echo ""
echo "── Anthropic ─────────────────────────────────────────────────────────────"
echo "  Get your API key at https://console.anthropic.com"
echo ""
ANTHROPIC_API_KEY=$(prompt "Anthropic API Key" ANTHROPIC_API_KEY)

echo ""
echo "── Pexels ────────────────────────────────────────────────────────────────"
echo "  Get your API key at https://www.pexels.com/api"
echo ""
PEXELS_API_KEY=$(prompt "Pexels API Key" PEXELS_API_KEY)

echo ""
echo "── Postmark ──────────────────────────────────────────────────────────────"
echo "  Get your API token at https://account.postmarkapp.com"
echo ""
POSTMARK_API_TOKEN=$(prompt "Postmark API Token" POSTMARK_API_TOKEN)

echo ""
echo "── Inbound email (optional) ──────────────────────────────────────────────"
echo "  If you want to forward booking emails to trips, enter your inbound domain."
echo "  Leave blank to skip (you can set this up later)."
echo ""
TRIP_EMAIL_DOMAIN=$(prompt "Trip email domain (e.g. mail.yourdomain.com)" TRIP_EMAIL_DOMAIN "")

# ── Generate secrets automatically ───────────────────────────────────────────

SECRET_KEY_BASE=$(openssl rand -hex 64)
AR_PRIMARY_KEY=$(openssl rand -base64 32)
AR_DETERMINISTIC_KEY=$(openssl rand -base64 32)
AR_KEY_DERIVATION_SALT=$(openssl rand -base64 32)
INBOUND_EMAIL_PASSWORD=$(openssl rand -hex 32)

# ── Write .env ────────────────────────────────────────────────────────────────

cat > "$ENV_FILE" <<EOF
# Generated by setup.sh — keep this file private, never commit it.

SECRET_KEY_BASE=${SECRET_KEY_BASE}

ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY=${AR_PRIMARY_KEY}
ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY=${AR_DETERMINISTIC_KEY}
ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT=${AR_KEY_DERIVATION_SALT}

GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}

ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
PEXELS_API_KEY=${PEXELS_API_KEY}

POSTMARK_API_TOKEN=${POSTMARK_API_TOKEN}
RAILS_INBOUND_EMAIL_PASSWORD=${INBOUND_EMAIL_PASSWORD}
TRIP_EMAIL_DOMAIN=${TRIP_EMAIL_DOMAIN}

SOLID_QUEUE_IN_PUMA=true
EOF

chmod 600 "$ENV_FILE"

echo ""
echo "✅  .env created."
echo ""
echo "Next steps:"
echo "  1. docker compose up -d"
echo "  2. Open http://localhost:3000"
if [ -n "$TRIP_EMAIL_DOMAIN" ]; then
  echo ""
  echo "  For inbound email, configure your Postmark webhook:"
  echo "  https://YOUR_PLAUSIBLE_HOST/rails/action_mailbox/postmark/inbound_emails"
  echo "  Basic auth password: ${INBOUND_EMAIL_PASSWORD}"
fi
echo ""
