service: daplanstan
image: geertclaes/daplanstan

servers:
  web:
    - remote.kwokah.com

proxy:
  ssl: false
  hosts:
    - whats.daplanstan.com
  healthcheck:
    path: /up
    interval: 5
    timeout: 10

deploy_timeout: 90

registry:
  username: geertclaes
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    SOLID_QUEUE_IN_PUMA: true

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole --include-password"

volumes:
  - "daplanstan_storage:/rails/storage"

asset_path: /rails/public/assets

builder:
  arch: amd64

ssh:
  user: tripel